# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4PyjzOTnmtrQsPBQ0AB_8yEiwJYNFnI
"""


import streamlit as st
import pandas as pd
from datetime import datetime

# Page Configuration
st.set_page_config(
    page_title="Growth Mindset Challenge",
    page_icon="🚀",
    layout="centered",
    initial_sidebar_state="expanded"
)

# Custom CSS for styling
st.markdown("""
<style>
    .stButton>button {
        background-color: #4CAF50;
        color: white;
        font-size: 16px;
        padding: 10px 24px;
        border-radius: 8px;
        transition: background-color 0.3s ease;
    }
    .stButton>button:hover {
        background-color: #45a049;
    }
    .stTextInput>div>div>input, .stTextArea>div>div>textarea {
        border: 2px solid #4CAF50;
        border-radius: 8px;
        padding: 10px;
    }
    .stMarkdown h1, .stMarkdown h2, .stMarkdown h3 {
        color: #4CAF50;
    }
    .stProgress>div>div>div {
        background-color: #4CAF50;
    }
</style>
""", unsafe_allow_html=True)

# App Title
st.title("🚀 Growth Mindset Challenge")
st.markdown("---")

# Introduction Section
st.header("What is a Growth Mindset?")
st.write("""
A **growth mindset** is the belief that your abilities and intelligence can be developed through hard work, perseverance, and learning from your mistakes.
This concept, popularized by psychologist Carol Dweck, encourages us to embrace challenges, learn from failures, and persist through difficulties.
""")

# Benefits of Growth Mindset
st.header("Why Adopt a Growth Mindset?")
st.write("""
- **Embrace Challenges:** View obstacles as opportunities to learn.
- **Learn from Mistakes:** Understand that mistakes are part of the learning process.
- **Persist Through Difficulties:** Stay determined even when things get tough.
- **Celebrate Effort:** Recognize the effort you put into learning, not just the results.
- **Stay Open-Minded:** Be curious and willing to adapt your approach.
""")

# User Input Section
st.header("Your Growth Mindset Journey")
st.write("Let's start your journey by setting some goals and reflecting on your challenges.")

# Input Fields
name = st.text_input("Enter your name:")
goal = st.text_area("What is your learning goal for this week?")
challenge = st.text_area("What challenges are you currently facing?")

# Save User Input
if st.button("Submit"):
    if name and goal and challenge:
        st.success("Thank you for sharing! Here's your plan to adopt a growth mindset:")

        # Display User's Plan
        st.subheader(f"{name}'s Growth Mindset Plan")
        st.write(f"**Goal:** {goal}")
        st.write(f"**Challenge:** {challenge}")
        st.write("""
        **Steps to Overcome:**
        1. Break your goal into smaller, manageable tasks.
        2. Reflect on your progress daily.
        3. Seek feedback from peers or mentors.
        4. Celebrate small wins along the way.
        """)

        # Save data to a CSV file
        data = {
            "Name": [name],
            "Goal": [goal],
            "Challenge": [challenge],
            "Date": [datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
        }
        df = pd.DataFrame(data)
        df.to_csv("user_data.csv", mode="a", header=not pd.read_csv("user_data.csv").shape[0], index=False)
    else:
        st.error("Please fill in all fields before submitting.")

# Progress Tracker
st.header("📊 Progress Tracker")
st.write("Track your progress toward your goals.")

# Load user data
try:
    user_data = pd.read_csv("user_data.csv")
    if not user_data.empty:
        st.write("### Your Progress")
        st.dataframe(user_data)

        # Visualize progress using a bar chart
        progress_chart = px.bar(
            user_data,
            x="Date",
            y="Name",
            title="Your Progress Over Time",
            labels={"Name": "User", "Date": "Date"},
            color="Name"
        )
        st.plotly_chart(progress_chart)
    else:
        st.info("No progress data found. Start by submitting your goals and challenges!")
except FileNotFoundError:
    st.info("No progress data found. Start by submitting your goals and challenges!")

# Daily Reflection Log
st.header("📝 Daily Reflection Log")
st.write("Log your daily reflections to track your growth.")

reflection = st.text_area("Write your reflection for today:")
if st.button("Log Reflection"):
    if reflection:
        st.success("Reflection logged successfully!")
        reflection_data = {
            "Name": [name],
            "Reflection": [reflection],
            "Date": [datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
        }
        df = pd.DataFrame(reflection_data)
        df.to_csv("reflection_data.csv", mode="a", header=not pd.read_csv("reflection_data.csv").shape[0], index=False)
    else:
        st.error("Please write a reflection before logging.")

# Motivational Quotes Section
st.header("💡 Motivational Quotes")
quotes = [
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "It’s not that I’m so smart, it’s just that I stay with problems longer. – Albert Einstein",
]

for quote in quotes:
    st.write(f"✨ {quote}")

# Footer
st.markdown("---")
st.write("Built with ❤️ by [Hanzala Afridi] using Streamlit")
